# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/20_plot.ipynb.

# %% auto 0
__all__ = ['partially_observed_time_series']

# %% ../nbs/20_plot.ipynb 3
import torch
import seaborn as sns
import matplotlib.pyplot as plt

# %% ../nbs/20_plot.ipynb 4
sns.set_theme()

# %% ../nbs/20_plot.ipynb 6
def partially_observed_time_series(
    observed_t: torch.Tensor,
    observed_y: torch.Tensor,
    to_predict_at_t: torch.Tensor
):
    
    _, axis = plt.subplots()
    
    sns.scatterplot(x=observed_t, y=observed_y, color='blue')
    
    for x in to_predict_at_t:
        axis.axvline(x, color='gray', linestyle='dashed')
        
    axis.set(xlabel='t', ylabel='observations')
    
    return axis
